# -*- coding: utf-8 -*-
"""salaryapp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdqldTOckLBrv6wmIfa3D3tRkSJ6U4nm
"""



import streamlit as st
import pickle
import numpy as np

# Set page config
st.set_page_config(page_title="Professional Salary Predictor", layout="centered")

# Load model and encoders
with open("model.pkl", "rb") as f:
    model = pickle.load(f)
with open("le_gender.pkl", "rb") as f:
    le_gender = pickle.load(f)
with open("le_edu.pkl", "rb") as f:
    le_edu = pickle.load(f)
with open("le_job.pkl", "rb") as f:
    le_job = pickle.load(f)

# UI Title
st.markdown("<h1 style='text-align: center; color: navy;'>💼 Professional Salary Prediction App</h1>", unsafe_allow_html=True)

st.markdown("---")

# User Inputs
col1, col2 = st.columns(2)

with col1:
    age = st.slider("Select Age", 18, 65, 30)
    gender = st.selectbox("Select Gender", le_gender.classes_)
    edu = st.selectbox("Select Education Level", le_edu.classes_)

with col2:
    exp = st.slider("Years of Experience", 0, 40, 5)
    job = st.selectbox("Select Job Title", le_job.classes_)

# Predict button
if st.button("Predict Salary"):
    try:
        # Encode inputs
        gender_enc = le_gender.transform([gender])[0]
        edu_enc = le_edu.transform([edu])[0]
        job_enc = le_job.transform([job])[0]

        features = np.array([[age, gender_enc, edu_enc, job_enc, exp]])
        prediction = model.predict(features)[0]

        st.success(f"💰 Estimated Salary: ₹{prediction:,.2f}")
    except Exception as e:
        st.error(f"Error: {e}")

# Footer
st.markdown("---")
st.markdown("<p style='text-align: center; color: gray;'>Built by Sakthi | Powered by Streamlit & Scikit-learn</p>", unsafe_allow_html=True)
